{{- if and .Values.javaApp.enabled .Values.javaApp.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-java-app" (include "java-data-stack.fullname" .)) .Values.javaApp.secret.name }}
  labels:
    {{- include "java-data-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  CASSANDRA_USERNAME: {{ .Values.javaApp.connections.cassandra.username | quote }}
  CASSANDRA_PASSWORD: {{ .Values.javaApp.connections.cassandra.password | quote }}
  KEYDB_PASSWORD: {{ .Values.javaApp.connections.keydb.password | quote }}
{{- end }}
