grafana:
  image:
    registry: registry.airgap.local
    repository: monitoring/grafana
    tag: 12.4.5-observability-plugins
    pullPolicy: IfNotPresent

  grafana.ini:
    analytics:
      reporting_enabled: false
      check_for_updates: false
      check_for_plugin_updates: false
    plugins:
      plugin_admin_enabled: false
      plugin_admin_external_manage_enabled: false

  plugins: []

  additionalDataSources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
      isDefault: true

    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local
      jsonData:
        derivedFields:
          - name: trace_id
            matcherRegex: "(?:trace_id|traceID|traceId)=([a-fA-F0-9]+)"
            datasourceUid: tempo
            url: "$${__value.raw}"

    - name: Tempo
      uid: tempo
      type: tempo
      access: proxy
      url: http://tempo.monitoring.svc.cluster.local:3100
      jsonData:
        httpMethod: GET
        tracesToLogsV2:
          datasourceUid: Loki
          spanStartTimeShift: "-1h"
          spanEndTimeShift: "1h"
          filterByTraceID: true
          filterBySpanID: false
        serviceMap:
          datasourceUid: Prometheus
