# Fast local/dev profile. No persistent storage.

cassandra:
  enabled: true
  image:
    repository: bitnamilegacy/cassandra
    tag: 5.0.5-debian-12-r7
    pullPolicy: IfNotPresent
  dbUser:
    user: cassandra
    password: "dev-cassandra-password"
  cluster:
    name: dev-cassandra
    datacenter: dc1
    seedCount: 1
  replicaCount: 1
  persistence:
    enabled: false
  initDB:
    01-keyspace.cql: |
      CREATE KEYSPACE IF NOT EXISTS app_dev
      WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};

keydb:
  enabled: true
  image:
    repository: bitnamilegacy/keydb
    tag: 6.3.4-debian-12-r24
    pullPolicy: IfNotPresent
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
  replica:
    replicaCount: 0

kafka:
  enabled: true
  image:
    repository: bitnamilegacy/kafka
    tag: 4.0.0-debian-12-r10
    pullPolicy: IfNotPresent
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
  controller:
    replicaCount: 1
    controllerOnly: false
    persistence:
      enabled: false
  broker:
    replicaCount: 0

javaApp:
  enabled: false
  image:
    repository: sample-java-app
    tag: "0.1.0"
    pullPolicy: IfNotPresent
  connections:
    cassandra:
      keyspace: app_dev
      password: "dev-cassandra-password"
    keydb:
      password: ""
